export const toolRegistry = [
  // Image
  { route: 'image', tool: 'edit', label: 'Image: Edit/Convert', path: '/image?tool=edit' },
  { route: 'image', tool: 'bulk', label: 'Image: Bulk (ZIP)', path: '/image?tool=bulk' },
  { route: 'image', tool: 'base64', label: 'Image: Base64', path: '/image?tool=base64' },
  { route: 'image', tool: 'pdf', label: 'Image: Images to PDF', path: '/image?tool=pdf' },
  { route: 'image', tool: 'colors', label: 'Image: Average/Dominant Colors', path: '/image?tool=colors' },
  { route: 'image', tool: 'picker', label: 'Image: Color Picker (Eyedropper)', path: '/image?tool=picker' },
  { route: 'image', tool: 'censor', label: 'Image: Photo Censor (Blur/Pixelate/Bar)', path: '/image?tool=censor' },
  { route: 'image', tool: 'svg', label: 'Image: SVG Tools (Blob/Pattern/SVG->PNG)', path: '/image?tool=svg' },
  { route: 'image', tool: 'favicon', label: 'Image: Favicon Validator', path: '/image?tool=favicon' },
  { route: 'image', tool: 'exif', label: 'Image: EXIF Viewer/Editor', path: '/image?tool=exif' },
  { route: 'image', tool: 'gif', label: 'Image: GIF Frame Extractor', path: '/image?tool=gif' },
  { route: 'image', tool: 'spriteanim', label: 'Image: Sprite Animator', path: '/image?tool=spriteanim' },

  // PDF
  { route: 'pdf', tool: 'merge', label: 'PDF: Merge', path: '/pdf?tool=merge' },
  { route: 'pdf', tool: 'split', label: 'PDF: Split', path: '/pdf?tool=split' },
  { route: 'pdf', tool: 'pages', label: 'PDF: Reorder/Rotate/Delete', path: '/pdf?tool=pages' },
  { route: 'pdf', tool: 'annotate', label: 'PDF: Text/Image/Watermark', path: '/pdf?tool=annotate' },
  { route: 'pdf', tool: 'preview', label: 'PDF: Preview/Extract Text', path: '/pdf?tool=preview' },
  { route: 'pdf', tool: 'toimages', label: 'PDF: PDF to Images', path: '/pdf?tool=toimages' },
  { route: 'pdf', tool: 'imgtopdf', label: 'PDF: Images to PDF', path: '/pdf?tool=imgtopdf' },
  { route: 'pdf', tool: 'scan', label: 'PDF: Scanned PDF Converter', path: '/pdf?tool=scan' },

  // Text
  { route: 'text', tool: 'case', label: 'Text: Case Converter', path: '/text?tool=case' },
  { route: 'text', tool: 'count', label: 'Text: Count', path: '/text?tool=count' },
  { route: 'text', tool: 'lines', label: 'Text: Line Tools', path: '/text?tool=lines' },
  { route: 'text', tool: 'find', label: 'Text: Find/Replace', path: '/text?tool=find' },
  { route: 'text', tool: 'diff', label: 'Text: Diff', path: '/text?tool=diff' },
  { route: 'text', tool: 'slug', label: 'Text: Slug', path: '/text?tool=slug' },
  { route: 'text', tool: 'lorem', label: 'Text: Lorem Ipsum', path: '/text?tool=lorem' },
  { route: 'text', tool: 'md', label: 'Text: Markdown Preview', path: '/text?tool=md' },
  { route: 'text', tool: 'data', label: 'Text: Data Tools (CSV/JSON)', path: '/text?tool=data' },
  { route: 'text', tool: 'fontpair', label: 'Text: Font Pair Finder (Offline)', path: '/text?tool=fontpair' },

  // CSS
  { route: 'css', tool: 'gradient', label: 'CSS: Gradient Generator', path: '/css?tool=gradient' },
  { route: 'css', tool: 'shadow', label: 'CSS: Box Shadow Generator', path: '/css?tool=shadow' },
  { route: 'css', tool: 'radius', label: 'CSS: Border Radius Generator', path: '/css?tool=radius' },
  { route: 'css', tool: 'bezier', label: 'CSS: Cubic Bezier Generator', path: '/css?tool=bezier' },
  { route: 'css', tool: 'clip', label: 'CSS: Clip Path Generator', path: '/css?tool=clip' },
  { route: 'css', tool: 'pattern', label: 'CSS: Background Pattern Generator', path: '/css?tool=pattern' },
  { route: 'css', tool: 'glass', label: 'CSS: Glassmorphism Generator', path: '/css?tool=glass' },
  { route: 'css', tool: 'loader', label: 'CSS: Loader Generator', path: '/css?tool=loader' },
  { route: 'css', tool: 'checkbox', label: 'CSS: Checkbox Generator', path: '/css?tool=checkbox' },
  { route: 'css', tool: 'switch', label: 'CSS: Switch Generator', path: '/css?tool=switch' },
  { route: 'css', tool: 'glitch', label: 'CSS: Text Glitch Effect', path: '/css?tool=glitch' },
  { route: 'css', tool: 'triangle', label: 'CSS: Triangle Generator', path: '/css?tool=triangle' },

  // Color
  { route: 'color', tool: 'hex', label: 'Color: HEX ↔ RGBA', path: '/color?tool=hex' },
  { route: 'color', tool: 'shades', label: 'Color: Shades Generator', path: '/color?tool=shades' },
  { route: 'color', tool: 'mixer', label: 'Color: Mixer', path: '/color?tool=mixer' },
  { route: 'color', tool: 'palette', label: 'Color: Palette Generator', path: '/color?tool=palette' },

  // Developer
  { route: 'developer', tool: 'base64', label: 'Dev: Base64', path: '/developer?tool=base64' },
  { route: 'developer', tool: 'encode', label: 'Dev: URL/HTML', path: '/developer?tool=encode' },
  { route: 'developer', tool: 'jwt', label: 'Dev: JWT Decoder', path: '/developer?tool=jwt' },
  { route: 'developer', tool: 'hash', label: 'Dev: Hash', path: '/developer?tool=hash' },
  { route: 'developer', tool: 'checksum', label: 'Dev: Checksum Suite', path: '/developer?tool=checksum' },
  { route: 'developer', tool: 'security', label: 'Dev: Encrypt/HMAC/TOTP', path: '/developer?tool=security' },
  { route: 'developer', tool: 'headers', label: 'Dev: HTTP Headers (CSP)', path: '/developer?tool=headers' },
  { route: 'developer', tool: 'env', label: 'Dev: .env Cleaner', path: '/developer?tool=env' },
  { route: 'developer', tool: 'schema', label: 'Dev: JSON Schema Validate', path: '/developer?tool=schema' },
  { route: 'developer', tool: 'password', label: 'Dev: Password', path: '/developer?tool=password' },
  { route: 'developer', tool: 'format', label: 'Dev: Format/Convert', path: '/developer?tool=format' },
  { route: 'developer', tool: 'regex', label: 'Dev: Regex', path: '/developer?tool=regex' },
  { route: 'developer', tool: 'uuid', label: 'Dev: UUID', path: '/developer?tool=uuid' },
  { route: 'developer', tool: 'time', label: 'Dev: Timestamp', path: '/developer?tool=time' },
  { route: 'developer', tool: 'cron', label: 'Dev: Cron', path: '/developer?tool=cron' },
  { route: 'developer', tool: 'beautify', label: 'Dev: Beautify/Minify', path: '/developer?tool=beautify' },

  // Coding
  { route: 'coding', tool: 'code2img', label: 'Coding: Code to Image', path: '/coding?tool=code2img' },
  { route: 'coding', tool: 'rnshadow', label: 'Coding: React Native Shadow', path: '/coding?tool=rnshadow' },
  { route: 'coding', tool: 'jsontree', label: 'Coding: JSON Tree Viewer', path: '/coding?tool=jsontree' },
  { route: 'coding', tool: 'og', label: 'Coding: Open Graph Meta Generator', path: '/coding?tool=og' },

  // WASM / heavy local processing
  { route: 'wasm', tool: 'ux', label: 'WASM: UX Kit', path: '/wasm?tool=ux' },
  { route: 'wasm', tool: 'imagepro', label: 'WASM: Image Pro', path: '/wasm?tool=imagepro' },
  { route: 'wasm', tool: 'pdfpro', label: 'WASM: PDF Pro', path: '/wasm?tool=pdfpro' },
  { route: 'wasm', tool: 'videopro', label: 'WASM: Video/Audio Pro', path: '/wasm?tool=videopro' },
  { route: 'wasm', tool: 'devpro', label: 'WASM: Dev Pro', path: '/wasm?tool=devpro' },
  { route: 'wasm', tool: 'design', label: 'WASM: Design Generator', path: '/wasm?tool=design' },
  { route: 'wasm', tool: 'privacy', label: 'WASM: Privacy/Offline', path: '/wasm?tool=privacy' },
  { route: 'wasm', tool: 'iconpack', label: 'WASM: Icon Pack Generator', path: '/wasm?tool=iconpack' },
  { route: 'wasm', tool: 'sprite', label: 'WASM: Sprite Sheet Builder', path: '/wasm?tool=sprite' },
  { route: 'wasm', tool: 'palette', label: 'WASM: Palette Extractor', path: '/wasm?tool=palette' },
  { route: 'wasm', tool: 'svgopt', label: 'WASM: SVG Optimizer', path: '/wasm?tool=svgopt' },
  { route: 'wasm', tool: 'pdfform', label: 'WASM: PDF Form Fill/Flatten', path: '/wasm?tool=pdfform' },
  { route: 'wasm', tool: 'sign', label: 'WASM: Signature Stamping UI', path: '/wasm?tool=sign' },
  { route: 'wasm', tool: 'ocr', label: 'WASM: OCR (Tesseract)', path: '/wasm?tool=ocr' },
  { route: 'wasm', tool: 'ffmpeg', label: 'WASM: FFmpeg Media Convert', path: '/wasm?tool=ffmpeg' },

  // Productivity
  { route: 'productivity', tool: 'qr', label: 'Prod: QR', path: '/productivity?tool=qr' },
  { route: 'productivity', tool: 'utm', label: 'Prod: UTM Builder + QR', path: '/productivity?tool=utm' },
  { route: 'productivity', tool: 'ics', label: 'Prod: ICS Event Generator', path: '/productivity?tool=ics' },
  { route: 'productivity', tool: 'timer', label: 'Prod: Pomodoro Timer', path: '/productivity?tool=timer' },
  { route: 'productivity', tool: 'barcode', label: 'Prod: Barcode', path: '/productivity?tool=barcode' },
  { route: 'productivity', tool: 'unit', label: 'Prod: Units', path: '/productivity?tool=unit' },
  { route: 'productivity', tool: 'tz', label: 'Prod: Time Zones', path: '/productivity?tool=tz' },
  { route: 'productivity', tool: 'calc', label: 'Prod: Calculator', path: '/productivity?tool=calc' },
  { route: 'productivity', tool: 'pct', label: 'Prod: Percent', path: '/productivity?tool=pct' },
  { route: 'productivity', tool: 'size', label: 'Prod: File Size', path: '/productivity?tool=size' },
  { route: 'productivity', tool: 'rename', label: 'Prod: File Renamer (ZIP)', path: '/productivity?tool=rename' },
  { route: 'productivity', tool: 'detect', label: 'Prod: Type + SHA-256', path: '/productivity?tool=detect' },

  // Social (offline generators)
  { route: 'social', tool: 'tweet', label: 'Social: Tweet Generator', path: '/social?tool=tweet' },
  { route: 'social', tool: 'igpost', label: 'Social: Instagram Post Generator', path: '/social?tool=igpost' },
  { route: 'social', tool: 'igstory', label: 'Social: Instagram Story Generator', path: '/social?tool=igstory' },
  { route: 'social', tool: 'revenue', label: 'Social: Ad Revenue Screenshot', path: '/social?tool=revenue' },
  { route: 'social', tool: 'igfilters', label: 'Social: Instagram Filters', path: '/social?tool=igfilters' },
  { route: 'social', tool: 'ytthumb', label: 'Social: YouTube Thumbnail Grabber', path: '/social?tool=ytthumb' },
  { route: 'social', tool: 'directdl', label: 'Social: Direct Media URL Downloader', path: '/social?tool=directdl' },

  // Misc
  { route: 'misc', tool: 'random', label: 'Misc: List Randomizer', path: '/misc?tool=random' },
  { route: 'misc', tool: 'iban', label: 'Misc: Fake IBAN Generator', path: '/misc?tool=iban' },
  { route: 'misc', tool: 'dice', label: 'Misc: Dice Roller', path: '/misc?tool=dice' },
  { route: 'misc', tool: 'password', label: 'Misc: Strong Random Password', path: '/misc?tool=password' },
]
